version: '3'
services:
  scheduler-1:
    image: cwash-demo/scheduler-demo:0.0.1-SNAPSHOT
    environment:
    - group.name=scheduler-demo
    - group.password=s3crEt
#    - managementCenter.url=http://mancenter:9090/mancenter
    ports:
    - "8080:8080"
    links:
    - "cassandra-1:cassie"
#    - "management-center:mancenter"
  scheduler-2:
    image: cwash-demo/scheduler-demo:0.0.1-SNAPSHOT
    environment:
    - group.name=scheduler-demo
    - group.password=s3crEt
#    - managementCenter.url=http://mancenter:9090/mancenter
    ports:
    - "8081:8080"
    links:
    - "cassandra-1:cassie"
#    - "management-center:mancenter"
  scheduler-3:
    image: cwash-demo/scheduler-demo:0.0.1-SNAPSHOT
    environment:
    - group.name=scheduler-demo
    - group.password=s3crEt
#    - managementCenter.url=http://mancenter:9090/mancenter
    ports:
    - "8082:8080"
    links:
    - "cassandra-1:cassie"
#    - "management-center:mancenter"
  cassandra-1:
    image: spotify/cassandra:latest
    ports:
    - "9042:9042"
    volumes:
    - ~/cassandra-1:/var/lib/cassandra
#    links:
#    - "management-center:mancenter"
  #management center
#  management-center:
#    image: hazelcast/management-center
#    # persisting mancenter users db folder to local disk
#    volumes:
#    - ~/mancenter3.8:/mancenter-3.8
#    environment:
#    - MANCENTER_DATA=/mancenter-3.8
#    # enable REST interface on management center
#    # http://docs.hazelcast.org/docs/latest-development/manual/html/Management/Clustered_REST_via_Management_Center.html
#    - JAVA_OPTS=-Dhazelcast.mc.rest.enabled=true
#    ports:
#    - 9090:8080